### ISSUE TITLE
plugin breaks after restarting PC

### ISSUE THREAD

**Issue by cdanesi** [fredemmott/StreamDeck-AudioSwitcher#10]
Every time I restart my PC, the plugin breaks completely. The only way to get it functional again is to completely uninstall and reinstall the plugin and reconfigure the settings. Attached a screenshot of the settings after a reboot.

![Capture](https://user-images.githubusercontent.com/7756260/67408560-2fa14900-f587-11e9-9727-aa3e4bebcc44.PNG)

**Comment by btastic** [comment]
Same problem here

**Comment by Fireeyeeian** [comment]
I have the same issue. I also tried manually installing the plugin and now I can't uninstall the plugin through stream deck or even by deleting the plugins folder...

**Comment by fredemmott** [comment]
Merging related issues into #19
