### ISSUE TITLE
Support for fallback devices / Switching between more than two devices

### ISSUE THREAD

**Issue by cerahmed** [fredemmott/StreamDeck-AudioSwitcher#106]
**Is your feature request related to a problem? Please describe.**
I normally switch between (primary) a wired headset while gaming and (secondary) a _wired_ Pebble Speaker (that can also operate over bluetooth).

I _frequently_ switch between using the Pebble Speaker wired and over BT (while the primary is the same wired headset) for reasons too detailed to mention. When I do so, I have to reprogram the button to switch to the BT-connected/Wired-connected Pebble speaker everytime.

**Describe the solution you'd like**
The plugin can implement switching between 3 devices,
or better allow for fallback devices (when the chosen one is not currently connected, go to the next chosen device).

Example of how this can be shown in the inspector view:

-> Direction:
-> Role:
-> Primary:
-> Primary Fallback 1:
-> Primary Fallback 2:
etc..
-> Secondary:
-> Secondary Fallback 1:
-> Secondary Fallback 2:
etc..

**Describe alternatives you've considered**
I've tried adding an additional AudioSwitcher button for when the external speaker is connected via Bluetooth, which works fine but takes real estate in my rather congested streamdeck profile.

**Comment by cerahmed** [comment]
Looking around the open issues, I realized that this feature could be solved with a better fuzzy matching logic as mentioned [in this issue](https://github.com/fredemmott/StreamDeck-AudioSwitcher/issues/89#issue-1419821831).

I will try to understand the source code and do some testing with other fuzzy matching logic.

**Comment by fredemmott** [comment]
Not going to do this: this can be done with multi actions and/or multi action switches: set the least preferred device first, then more preferred
