### ISSUE TITLE
Feature Request: Ability to control Line-In (or other device specific volume)

### ISSUE THREAD

**Issue by wykydtronik** [fredemmott/StreamDeck-AudioSwitcher#11]
Ability to control Line-In (or other device specific volume)

**Comment by fredemmott** [comment]
You might be interested in github.com/fredemmott/StreamDeck-AudioMute

I'm not currently planning on more general volume control, and consider it out of scope for the current plugins.

**Comment by fredemmott** [comment]
Also, I'm sorry it took so long to respond; at some point last year, the GitHub notifications settings for several of my personal projects were changed - none of my actual work projects were affected, so I did not notice until mentioned on a new issue.
