### ISSUE TITLE
Can't switch to blackmagic

### ISSUE THREAD

**Issue by computergeektroy** [fredemmott/StreamDeck-AudioSwitcher#110]
I keep trying to switch my audio input to Video Assist 5" 3G, but it will never take. I'm wondering if it's because of the name of the device? Every other device I try works, but this one will not. I tried fuzzy and Exact. I've tried different computers as well.

[New Recording - 7/24/2023, 2:13:04 PM](https://vimeo.com/848135647/330cb2f7e2)

The device is linked below though USB to a mac laptop.
https://www.blackmagicdesign.com/products/blackmagicvideoassist/techspecs/W-VASS-05

**Comment by fredemmott** [comment]
If you have multiple devices with the same name, it’s a macos limitation as there is no other way to identify. The plugin has no problem with weird names.

if you’re also unable to select the device with “audio midi setup”, you need to contact black magic support.

closing as either way, nothing to do on the plugin side.
