### ISSUE TITLE
Unable to connect to the audio router. (start .exe manually)

### ISSUE THREAD

**Issue by sander1095** [fredemmott/StreamDeck-AudioSwitcher#111]
**Describe the bug**
When the stream deck starts up, the plugin doesn't work. Streamdeck reports the following error:

```
Unable to connect to the audio router.
You can manually start the audio router by opening 'C:\Program Files\Elgato\Volume Controller\ElgatoAudioControlServer.exe'.
```

**To Reproduce**
Start PC
Open stream deck application.

**Expected behavior**
I expect the application to work out of the box without having to execute an `.exe` manually.

**Debugging Information**
![image](https://github.com/fredemmott/StreamDeck-AudioSwitcher/assets/7312681/af1601cd-79ed-4f9d-a010-4a3c988c2220)

**Log File**
The mentioned log file doesn't exist. I only have `com.elgato.volume-controller0.log`:

```
14:12:00.753 Audio Router is not running!
```

** Operating System **
Windows 10 64-bit

**Additional context**
None

**Comment by fredemmott** [comment]
That’s a different plugin, made by elgato, not me. You want elgato support
