### ISSUE TITLE
Crashing on Windows Devices

### ISSUE THREAD

**Issue by pnorms** [fredemmott/StreamDeck-AudioSwitcher#112]
Faulting application

Pressing audio up or down buttons

The plugin should not crash

Faulting application path: C:\Users\username\AppData\Roaming\Elgato\StreamDeck\Plugins\com.fredemmott.audiooutputswitch.sdPlugin\sdaudioswitch.exe
Faulting module path: C:\Users\username\AppData\Roaming\Elgato\StreamDeck\Plugins\com.fredemmott.audiooutputswitch.sdPlugin\sdaudioswitch.exe
Report Id: 9721519b-3f6c-4849-8b1d-7ef007604a2f
Faulting package full name:
Faulting package-relative application ID:
Faulting application name: sdaudioswitch.exe, version: 3.1.3.66, time stamp: 0x6325ffd0
Faulting module name: sdaudioswitch.exe, version: 3.1.3.66, time stamp: 0x6325ffd0
Exception code: 0xc0000005
Fault offset: 0x000000000002b134

**Comment by fredemmott** [comment]
Can you provide a minidump or a way to reproduce this?

**Comment by cgalbreath** [comment]
This error is also coming out for me and sometimes its causing a BSOD which is interesting...

**Comment by fredemmott** [comment]
If this triggers a BSOD you have a buggy driver, contact your manufacturer’s customer service.

**Comment by fredemmott** [comment]
Locking as it’s a generic unactionable error; if anyone has crashes, open separate tickets with dumps, don’t comment on existing tickets
