### ISSUE TITLE
DisplayPort audio outputs not being listed

### ISSUE THREAD

**Issue by ffreitasit** [fredemmott/StreamDeck-AudioSwitcher#113]
**Describe the bug**
DisplayPort audio outputs not being listed

**To Reproduce**
Try to select a DisplayPort audio device on the list for the primary device or the secondary device

**Expected behavior**
It should list the DisplayPort device and be able to switch the audio to that device

** Operating System **
MacOS Sonoma 14.2.1

**Additional context**
![Screenshot 2024-01-09 at 17 06 08](https://github.com/fredemmott/StreamDeck-AudioSwitcher/assets/184118/cf941b2b-cc7f-4033-906b-9739b4da5c01)

![Screenshot 2024-01-09 at 17 06 20](https://github.com/fredemmott/StreamDeck-AudioSwitcher/assets/184118/d8846c9c-4056-4b9a-b079-e05634857ba7)

In the example above, the device "HP M34d WQHD" is not listed as a device.

**Comment by ryanpsw** [comment]
I am having the same issue with my HDMI outputs with v3.2.0 as well. v3.1.3 can identify all outputs just fine. MacOS Sonoma 14.2.1
