### ISSUE TITLE
Same device is often "unplugged" and shown up as new device; Hotkey not useable anymore

### ISSUE THREAD

**Issue by 0x1234567890** [fredemmott/StreamDeck-AudioSwitcher#117]
**Describe the bug**
After a few days it happens that the hotkey on my StreamDeck no longer works. 
An exclamation mark is then displayed when changing the output device.

In order for it to work again, the headset or the loudspeaker must be re-stored. 

The same device is then displayed twice in the StreamDeck software. Once as available and once as "unplugged". 
I can always switch it back and forth, the error always occurs again after a while. 
This is not the purpose of a hotkey. Then I can also switch the output device manually...

I also tried to set it on matching "fuzzy" and "exact" but still have the same issue
What can i do?

**To Reproduce**
The error cannot be reproduced. It just happens by itself after a few days

**Debugging Information**
![NVIDIA_Share_tBx5gh0b6G](https://github.com/fredemmott/StreamDeck-AudioSwitcher/assets/1353407/4fa18401-8cd2-4f01-a0ee-5f2a618245ba)

**Log File**
[logs.zip](https://github.com/fredemmott/StreamDeck-AudioSwitcher/files/14551392/logs.zip)

** Operating System **
Windows 10 Professional, 64-bit

**Comment by fredemmott** [comment]
Driver bug. Use fuzzy matching if your driver reports it’s a different device.
