### ISSUE TITLE
Audio Switcher not in Sync with MacOS Sound Effect Routing

### ISSUE THREAD

**Issue by chrishutchins** [fredemmott/StreamDeck-AudioSwitcher#119]
**Describe the bug**
When toggling audio devices, the audio device for "Play sound effects through" doesn't change. 

**To Reproduce**
Walkthrough of issue https://www.loom.com/share/84409802d2a24123afbbcb626663f966

**Expected behavior**
I would expect the sound effect output to stay on "Selected Sound Output Device", but alternatively it could cycle through the outputs I switch between.

** Operating System **
MacOS 14.4.1

**Comment by fredemmott** [comment]
This is a macos bug that can only be fixed by apple; it's also reproducible with the built-in "audio midi setup" app

**Comment by chrishutchins** [comment]
@fredemmott thanks for the quick reply! Any bug report for Apple I can pile on to?

**Comment by fredemmott** [comment]
Unfortunately no, Apple apparently only tell you the issue number if you're the first to report it.
