### ISSUE TITLE
Buttons set devices get switched to different ones

### ISSUE THREAD

**Issue by Tofiel** [fredemmott/StreamDeck-AudioSwitcher#12]
A quite often I have to re-setup configuration of buttons because they are no longer bind to devices that they used to be set up. my configuration: TV speakers, wired headphones and two sets of Bluetooth headsets that are recognized as two devices (each one) headset and stereo headphones. I think it could be related to the order of devices that they appear after wireless/wired headphones are disconnected/reconnected. Could plugin compare devices against devices' names? As names are not renamed often (or not at all) it should be more accurate than changing the configuration after the battery gets discharged.

**Comment by fredemmott** [comment]
Merging related issues into #19

Names are not more accurate, and Microsoft's documentation says the device IDs being used survive unplug/replug/reboot; this is clearly not happening.

Do you have multiple devices of the same/similar model? If so, any idea if windows considers them to have the same (or no) serial number?

**Comment by fredemmott** [comment]
Also, I'm sorry it took so long to respond; at some point last year, the GitHub notifications settings for several of my personal projects were changed - none of my actual work projects were affected, so I did not notice until mentioned on a new issue.

**Comment by fredemmott** [comment]
Closing for #19 - please feel free to re-open (or comment on #19 if it seems related) with more information.
