### ISSUE TITLE
Fuzzy is doing the exact oppsite.

### ISSUE THREAD

**Issue by luftkeks** [fredemmott/StreamDeck-AudioSwitcher#120]
**Describe the bug**
When the Fuzzy Device Matching pattern is used its going for the first letter and therefore sometimes switching to my secondary monitore.

**To Reproduce**
1. be not on your display audio device
2. have your grafik card have some messup
3. switch to grafik card audio device - notice it's search for the one and not for the string afterwards

**Expected behavior**
Search for the String and ignore the first 4 letters if first letter is a 1

** Operating System **

Windows 11 Professional, 64-bit"

**Comment by fredemmott** [comment]
Step 2 is not reproducible, and this isn’t how fuzzy matching works - it ignores numeric suffices. Unfortunately this can’t be acted on.

If you need fuzzy matching, you should ask your device manufacturer to fix their driver so that IDs don’t change.
