### ISSUE TITLE
Icon displayed switches back to primary icon after a while

### ISSUE THREAD

**Issue by hschieck** [fredemmott/StreamDeck-AudioSwitcher#13]
When using the toggle function to switch from primary device to secondary device, the icon set for the secondary device is shown only for a short time, then the icon set for the primary device is shown again. The actual switching back and forth between the audio devices is working though.

![20200106_222009](https://user-images.githubusercontent.com/12649468/71849855-545f8400-30d3-11ea-8f73-3c54303da554.gif)

Current setup:
    Title: _not set_
    Direction: Output
    Role: Default
    Primary: Lautsprecher (2-Logitech USB Headset)
    Secondary: Realtek Digital Output(Optical)(Realtek High Definition Audio)

**Comment by fredemmott** [comment]
Merging related issues into #19

**Comment by fredemmott** [comment]
Also, I'm sorry it took so long to respond; at some point last year, the GitHub notifications settings for several of my personal projects were changed - none of my actual work projects were affected, so I did not notice until mentioned on a new issue.
