### ISSUE TITLE
List currently disconnected devices

### ISSUE THREAD

**Issue by blueal** [fredemmott/StreamDeck-AudioSwitcher#16]
I have lots of audio devices that are occasionally disabled and/or unplugged from my computer, I was swapping between with batch scripts before finding this plugin. Unfortunately disabled or unplugged devices get _removed_ from the drop down menus on the buttons and are **randomly** set to another enabled audio device. Is there a way that the drop down menus will list ALL audio devices available, even those not enabled or plugged in? Or at least retain them so that I can swap to it when I reconnect my Bluetooth headphones.

**Comment by blueal** [comment]
Because of this design flaw this plugin is unfortunately useless to me. I'm now back to having dedicated buttons attached to batch scripts for each device

**Comment by fredemmott** [comment]
Merging related issues into #19

**Comment by fredemmott** [comment]
> Is there a way that the drop down menus will list ALL audio devices available, even those not enabled or plugged in? 

Renaming to cover this, which isn't in #19 

https://github.com/fredemmott/StreamDeck-AudioSwitcher/blob/f673365beee287dd178cb4225fe6ab8c15c1f1f3/Sources/Windows/AudioFunctions.cpp#L81 is how the device list is fetched

This specifies DEVICE_STATE_ACTIVE; per https://docs.microsoft.com/en-us/windows/win32/api/mmdeviceapi/nf-mmdeviceapi-immdeviceenumerator-enumaudioendpoints , 'disabled' (via control panel) 'not present' (usb/bluetooth device that is not attached), and 'unplugged' (audio device present, but e.g. nothing plugged in to the headphone jack) are also accessible, so this should be doable

**Comment by fredemmott** [comment]
Also, I'm sorry it took so long to respond; at some point last year, the GitHub notifications settings for several of my personal projects were changed - none of my actual work projects were affected, so I did not notice until mentioned on a new issue.

**Comment by fredemmott** [comment]
Heh, definitely going to need some filtering and different UI here - the APIs reporting 112 devices on my system.

**Comment by fredemmott** [comment]
Before:

![Active-devices-only](https://user-images.githubusercontent.com/360927/83337762-d747cd80-a272-11ea-9e0a-d1176edf3da8.png)

After:

Filtering out devices with no name (which I'm not digging into at present), I'm left with 57
![all-devices](https://user-images.githubusercontent.com/360927/83337763-dadb5480-a272-11ea-879f-8f5453859459.png)

**Comment by fredemmott** [comment]
At least if you have an nvidia card, windows appears to remember a distinct audio device for every HDMI/DisplayPort monitor/projector/.... you've ever plugged in :/ Wonder if I can filter by 'last <n> months', or just only show:
- ones that are currently usable
- ones that are not currently usable, but have been selected for this plugin

**Comment by fredemmott** [comment]
@blueal what I've gone for at the moment is to show an input/output if any of these is true:

- it is usable right now
- it's not usable right now, but the current button is configured to use it
- the sound card is present, but the output isn't connected - for example, motherboards often tell windows "I have a headphone socket, but nothing is plugged in to it"

It will not show inputs/outputs:
- if the sound card is not attached to the computer (e.g. unplugged USB devices, possibly bluetooth)
- if they explicitly disabled in control panel
- ... unless the current button is configured to use them

Does this solve the problems you've been having? I'm trying to balance "show anything useful" with "don't show 100 irrelevant devices that were plugged in once 50 years ago"

**Comment by blueal** [comment]
@fredemmott Thank you so much for working on this! I believe this would cover about 90% of my use case, probably all of it if _"unless the current button is configured to use them"_ function works as expected.

The real kicker previously was my Bluetooth Headphones and extending my display to the TV over NVIDIA HDMI. Anytime I turn off my headphones Windows reports the device as Disconnected, while it reports the TV as "Not Plugged In". I think you've fixed that issue!

Is there a beta version I could download and try out?

**Comment by fredemmott** [comment]
v2.3 at https://github.com/fredemmott/StreamDeck-AudioSwitcher/releases/latest should fix this

**Comment by fredemmott** [comment]
@blueal if it doesn't quite work for you but you're comfortable with JS, all the filtering except for "ignore devices without a name" part is in `%appdata%\Elgato\StreamDeck\Plugins\com.fredemmott.audiooutputswitch.sdPlugin\propertyinspector\index.html` - around here:

https://github.com/fredemmott/StreamDeck-AudioSwitcher/blob/56f904c13cb1788725f6dddf9b621c3bb34b4f19/Sources/sdPlugin/propertyinspector/index.html#L136

**Comment by blueal** [comment]
I was reading some logs in event viewer after encountering audio issues and a blue screen when I noticed this new release is absolutely flooding the logs with Errors and crash reports. I couldn't tell if it's related to my blue screen but it doesn't look good.

![Crash Logs](https://user-images.githubusercontent.com/4614311/83382333-b7f69080-a397-11ea-8a1e-4184ce00dc6a.png)
![Error Logs](https://user-images.githubusercontent.com/4614311/83382491-0e63cf00-a398-11ea-8924-88e99994e26b.png)

> Faulting application name: sdaudioswitch.exe, version: 0.0.0.0, time stamp: 0x5ed2df3d
Faulting module name: sdaudioswitch.exe, version: 0.0.0.0, time stamp: 0x5ed2df3d
Exception code: 0xc0000005
Fault offset: 0x000000000005c5ac
Faulting process id: 0x2e8c
Faulting application start time: 0x01d637de6496b869
Faulting application path: C:\Users\myusername\AppData\Roaming\Elgato\StreamDeck\Plugins\com.fredemmott.audiooutputswitch.sdPlugin\sdaudioswitch.exe
Faulting module path: C:\Users\myusername\AppData\Roaming\Elgato\StreamDeck\Plugins\com.fredemmott.audiooutputswitch.sdPlugin\sdaudioswitch.exe
Report Id: a41f4e61-b70b-4cee-bdb7-4cad80b7321f
Faulting package full name: 
Faulting package-relative application ID:

**Comment by fredemmott** [comment]
Are these crashes:
- when pressing a button?
- when the stream deck window is open and showing properties for the plugin?
- when something else changes the active audio device?

**Comment by blueal** [comment]
The crashes appear to occur when I change audio devices, either automatically or when I reconnect one of my devices, not via pressing any buttons. It doesn't seem to matter what screen the StreamDeck is on.

One interesting thing to note is that I defaultly have no audio device connected to my PC. It's entirely possible that the plugin crashes while I'm auto switching in and out of this state.

**Comment by fredemmott** [comment]
That's fairly likely; any chance you have any familiarity with C++?

https://github.com/fredemmott/StreamDeck-AudioSwitcher/blob/553505e3ba67b5ab9850ad892c4db6a765630b71/Sources/AudioFunctions.cpp#L165 and https://github.com/fredemmott/StreamDeck-AudioSwitcher/blob/553505e3ba67b5ab9850ad892c4db6a765630b71/Sources/AudioFunctions.cpp#L345 are likely problematic - both for null device pointer, and null device ID string (if the latter, https://github.com/fredemmott/StreamDeck-AudioSwitcher/blob/553505e3ba67b5ab9850ad892c4db6a765630b71/Sources/AudioFunctions.cpp#L29 should be changed)

If you're not comfortable poking those, I can add more safety checks and hope it fixes it - I won't be able to reproduce that problem.

**Comment by blueal** [comment]
My C++ Experience ends with data structures, so this might be just beyond my limits,. But I'll dive into it as a challenge.

**Comment by fredemmott** [comment]
It’s likely just a null pointer, and *probably* one of those two places. I’ll add checks at the weekend if you’re not able to find it sooner

**Comment by fredemmott** [comment]
[com.fredemmott.audiooutputswitch.streamDeckPlugin.zip](https://github.com/fredemmott/StreamDeck-AudioSwitcher/files/4740157/com.fredemmott.audiooutputswitch.streamDeckPlugin.zip)

Does this fix it?

**Comment by fredemmott** [comment]
@blueal ^ did that update fix it ?

**Comment by blueal** [comment]
@fredemmott Sorry, been very busy this week.
It does seem to be noticeably more stable. I've noted the following conditions:
| Condition  | Result |
| ------------- | ------------- |
| No Audio Device  | ✔  |
| Connect Audio Device  | ❓  |
| Disconnect Audio Device | ❌ |

It seems to all work fine until I change the state of the audio devices. Connecting an Audio device only sometimes causes a crash (such as connecting my TV but not when I connect my Bluetooth headphones). Disconnecting practically always results in a crash, but staying with everything disconnected doesn't cause a crash, and is stable. I've noticed that It has a tendency to stay crashed and "Freeze" the button icons for quite some time. Going to the Stream Deck software and clicking on the button shows it taking a good 15 seconds to restart the plugin before it starts working again.

**Comment by fredemmott** [comment]
>  Disconnecting practically always results in a crash

Is this when disconnecting *the last* device - or if for example you have two devices and remove one?

**Comment by blueal** [comment]
Just the first and last device connected. I tested it with multiple devices connected and that seems to work fine.

**Comment by fredemmott** [comment]
Can reproduce by disabling the last recording device.

Funnily enough, that also crashes the windows sound control panel :D

**Comment by fredemmott** [comment]
Actually no, I can't reproduce that with this plugin (device switcher), but can with the mute toggle

**Comment by fredemmott** [comment]
For that plugin (which has some shared code), crashes are only reliable if the property inspector open. Will check if that's the same here.

**Comment by fredemmott** [comment]
https://github.com/fredemmott/StreamDeck-AudioMute/releases/tag/v2.3 fixes the issue there

**Comment by fredemmott** [comment]
@blueal if https://github.com/fredemmott/StreamDeck-AudioSwitcher/releases/tag/v2.4 does not fix it:
- replace with the debug version
- enable mini dumps : https://www.windows10forums.com/articles/how-to-enable-minidump-logs-in-windows-10.50/
- if it crashes, attach the dump here, or email, dropbox etc.
