### ISSUE TITLE
App Specific Output

### ISSUE THREAD

**Issue by justweb1** [fredemmott/StreamDeck-AudioSwitcher#17]
I would love to see an option to change the output for specific applications. Example, a toggle that changes the output of Spotify from the default output to an output I use for OBS input.

**Comment by fredemmott** [comment]
I'm not planning on working on this, but as long as it's not a substantial amount of code, and uses APIs supported by Microsoft, I'd definitely be interesed in pull requests.

Also, I'm sorry it took so long to respond; at some point last year, the GitHub notifications settings for several of my personal projects were changed - none of my actual work projects were affected, so I did not notice until mentioned on a new issue.

**Comment by fredemmott** [comment]
https://github.com/File-New-Project/EarTrumpet appears to do something similar, and could be a useful source for API information

**Comment by fredemmott** [comment]
Appears to be SetPersistedDefaultAudioEndpoint in the undocumented IAudioPolicyConfigFactory interface

**Comment by fredemmott** [comment]
@davuxcom if you don't mind, how did you discover these interfaces? The old COM explorer tool?

**Comment by fredemmott** [comment]
Closing; this is supported by https://github.com/BarRaider/streamdeck-wintools
