### ISSUE TITLE
MacOS support on the roadmap?

### ISSUE THREAD

**Issue by jbeurel** [fredemmott/StreamDeck-AudioSwitcher#18]
Hello @fredemmott 
Have you planned MacOS support?
I never developed StreamDeck plugin but if I want to help you, what should I do first?
Thanks a lot.

**Comment by fredemmott** [comment]
I'm not generally planning any new features, however as long as they don't substantially affect what needs testing for a new release, I'd appreciate pull requests. This wouldn't be a substantial burden.

https://github.com/fredemmott/StreamDeck-AudioSwitcher/blob/master/Sources/AudioFunctions.h lists what needs adding

**Comment by fredemmott** [comment]
Since you filed this, I updated the plugin so it builds with CMake and uses the same version of shared code as my Discord plugin; while the audio functions still need porting, it does help as I do support the Discord plugin on MacOS, so the shared code and build system should now 'just work'.

**Comment by fredemmott** [comment]
You might want to follow https://github.com/fredemmott/StreamDeck-AudioMute/issues/1 - this plugin shares the same audio library, and I'm primarily working on portability there for now.

**Comment by matheustavaresdev** [comment]
Any updates on this perhaps?

**Comment by fredemmott** [comment]
There's been a lot of work on the other plugin and it's nearly there; the only known remaining problem (that will also affect this one) is that macos does not report known devices that are not present, so it will forget the configured device if not plugged in.

It's largely a matter of spare time; this is a hobby project, and right now most of my time is going into moving - if you happen to have javascript or type script experience, it would probably be relatively straightforward to fix; I think that the data could be saved by the property inspector (see Elgato's SDK docs for details)

**Comment by fredemmott** [comment]
mute plugin's done (https://github.com/fredemmott/StreamDeck-AudioMute/releases/tag/v3.0.0rc3) , this one's next :)

**Comment by fredemmott** [comment]
https://github.com/fredemmott/StreamDeck-AudioSwitcher/releases/tag/v3.0rc1
