### ISSUE TITLE
Endpoint ID stability issues/alternatives

### ISSUE THREAD

**Issue by fredemmott** [fredemmott/StreamDeck-AudioSwitcher#19]
This plugin uses [endpoint ID strings](https://docs.microsoft.com/en-us/windows/win32/coreaudio/endpoint-id-strings) to identify specific audio devices.

Per Microsoft's documentation, this:
- uniquely identifies the device among all audio endpoint devices in the system.
- lasts as long as the device is *installed* (which is not the same as pluggined in)
- changes if the device is explicitly uninstalled
- remains unchanged across system restarts
- remained unchanged for a USB audio device remains unchanged if the user unplugs the device and plugs it back in.

Based on #16, #13,#12, #10, this is not the case, and audio device IDs are changing.

Using user-friendly names to identify devices are not a solution: they change more frequently; at best, it would be breaking things for more users to fix it for others.

**Comment by fredemmott** [comment]
Based on @blueal's observation in #16, this might have been happening if the property inspector open, which is particularly likely on reboot etc if it is the top-left plugin (which it isn't for me, explaining why I've not see any of these, and means this might actually be the same issue)

**Comment by fredemmott** [comment]
@cdanesi, @btastic, @Fireeyeeian, @hschieck, @tofiel : I think v2.3 at https://github.com/fredemmott/StreamDeck-AudioSwitcher/releases/latest will fix the issues you've reported; I'd appreciate any feedback.

**Comment by hschieck** [comment]
Everything is working fine for me now. Thank you very much for fixing the plugin - I think it's very useful.
