### ISSUE TITLE
Feature Request: make it possible to set both roles simultaneously

### ISSUE THREAD

**Issue by altano** [fredemmott/StreamDeck-AudioSwitcher#2]
I'd like to check both Default and Communications and toggle BOTH when pressing the button. I don't split audio between communication and normal audio so I'd like everything from my Skype audio to my game audio to go through the same device. This would let me do that.

**Comment by fredemmott** [comment]
This has similar issues to #3, but here, it would probably be reasonable to treat the 'default' device as the active one if they're inconsistent

**Comment by Hogesyx** [comment]
This would be extremely useful for more complex audio setup. Currently I am using a multi action to stack them but it does not have the graphical feedback.

**Comment by morganscruggs** [comment]
IF this is possible, it would also be good to make input and output check boxes as well.  Then you can fully switch audio devices with 1 button.

**Comment by fredemmott** [comment]
It's definitely possible, and I'd happily consider merging pull requests for this.

**Comment by spencerhooks** [comment]
This would be useful for me too. Unfortunately, I'm not enough of a developer to make the change myself.

**Comment by PianomanEric** [comment]
Hi Fred! Are you still considering adding this as a feature? I love how much easier this has made switching between my headphones and my speakers, but it drives me nuts that my Discord call audio stays on my headphones. I'd love to have the ability to toggle default and communications roles simultaneously instead of having to use a button for each.

**Comment by fredemmott** [comment]
I'm not planing on working on this feature, however if there's a good pull request implementing it, I'll be happy to merge it.

**Comment by fredemmott** [comment]
I don't think this is necessary: this can be done with multi actions and multi action switches, and the 'set audio device' action. This avoids the issues surrounding partial success as mentioned in #3
