### ISSUE TITLE
VCRUNTIME140_1.dll was not found

### ISSUE THREAD

**Issue by larosa360** [fredemmott/StreamDeck-AudioSwitcher#20]
**Describe the bug**
Both I and my room mate are experiencing a system error stating that code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem.

**To Reproduce**
This alert is appearing on startup and when the stream deck software is started.

**Debugging Information**
Screenshot: https://i.imgur.com/zLknon9.png

**Log File**
https://gist.github.com/larosa360/2ff964c5b14b1d9682c934fe08bed8fb

** Operating System **
Windows 10 Pro

**Comment by larosa360** [comment]
I forgot to put this in the describe section...

This alert was appearing on version 2.2, I uninstalled the item and installed version 2.4 but am still receiving this error.

**Comment by fredemmott** [comment]
Installing vc_redist.x64.exe from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads should resolve this; I'll look into including them in the next release.

**Comment by fredemmott** [comment]
This should be fixed by [v2.5](https://github.com/fredemmott/StreamDeck-AudioSwitcher/releases/latest)
