### ISSUE TITLE
Selection boxes don't appear

### ISSUE THREAD

**Issue by GarlicButter2507** [fredemmott/StreamDeck-AudioSwitcher#21]
Hello,

Upon dragging the plugin onto the deck it enables me to rename it and change the icon, however, the input/output, default,comms and selection boxes don't appear.

I am on the latest version of streamdeck 4.7.0.12981 so don't understand what's wrong.

See the below picture as proof.

Thanks
![Annotation 2020-06-17 115721](https://user-images.githubusercontent.com/67052990/84890027-bca68e80-b091-11ea-87a0-61c38e04bd05.png)

**Comment by fredemmott** [comment]
Does [v2.5](https://github.com/fredemmott/StreamDeck-AudioSwitcher/releases/latest) solve this?

If not:

-  are you using 32-bit or 64-bit windows?
- what is the full version of windows that you are using? See https://support.microsoft.com/en-us/help/13443/windows-which-version-am-i-running for details

**Comment by GarlicButter2507** [comment]
Yes I must've been running an older version, that fixed the issue! Thanks!

**Comment by fredemmott** [comment]
Thanks - that version is newer than your issue, so you probably were on the latest at the time :)
