### ISSUE TITLE
I have to uninstall and reinstall after every pc restart to get audio mute button working 

### ISSUE THREAD

**Issue by Rozsy** [fredemmott/StreamDeck-AudioSwitcher#23]
**Describe the bug**

EDIT: THIS ONLY EFFECTS THE VERSION FROM THE INSTALL MORE MODS IN THE STREAM DECK 2.4 IF YOU INSTALL THE 2.5 RELEASE MANUALLY FROM HERE IT SEEMS TO BE FIXED 
I get a yellow warning indicator instead of the Audio mute working when i restart the computer, going into "more actions" - "Audio mute", uninstall then install, button works fine until i restart the pc again, button never gets deleted on uninstall, its a simple process to get working albeit annoying 
It's the only application to do this, all others work fine. Everything is upto date.

**Debugging Information**
--

**Log File**
08:39:45.275   ESDCustomPluginCommunication::onMessageReceived(): Plugin 1F8D7E7C28965D00B7F5BF4DF6319A98 is now connected
08:39:53.403   ESDCustomPlugin::StartPlugin::<lambda_0b565748c80c245c6dacbb627626632b>::operator ()(): The plugin 'Voicemod' crashed with code 1:-1073740791
08:39:53.403   ESDCustomPlugin::StartPlugin::<lambda_0b565748c80c245c6dacbb627626632b>::operator ()(): Restarting plugin 'Voicemod'
08:39:53.461   ESDCustomPluginCommunication::onMessageReceived(): Plugin 4AE2CF0AB1ABB202DCF414ED66D4218A is now connected
08:39:58.190   ESDAppStoreManager::UpdateAppStorePlugins():    Check for Plugin Store updates
08:40:17.629   ESDCustomPluginCommunication::onMessageReceived(): Plugin 3047CDAF94A4D248BB4119F21B8DBEBA is now connected
08:40:17.639   ESDCustomPluginCommunication::onMessageReceived(): Plugin 9439951257154460A02ACA6CBBD1CC26 is now connected
09:55:19.446   ESDActionsGridViewModel::onKeyPressed():        Key 11 pressed: com.fredemmott.micmutetoggle.toggle

09:55:49.360   EGQTCredentialStore::DeletePasswordWithServerAndUserName(): CredDelete() - GetLastError() 1168
09:55:49.750   ESDActionRegistry::CreateNewAction():           Trying to create an action from an unknown type com.fredemmott.micmutetoggle.toggle
09:55:52.092  ESDCustomPluginCommunication::onMessageReceived(): Plugin 547C0B7BFD55AEBD9BD68441FFA6E169 is now connected
09:55:53.801  ESDActionsGridViewModel::onKeyPressed():        Key 11 pressed: com.fredemmott.micmutetoggle.toggle

** Operating System **

1909 windows 10 home
stream deck firmware up to date
stream deck software version 4.8.1.13027

**Comment by fredemmott** [comment]
Thanks; I've asked Elgato to update the store version

**Comment by JoPe72** [comment]
Hi

Unfortunately I am still seeing this issue even though I am on version 3.0. After every restart the settings fields are gone and when I press the button I get the yellow triangle
![2021-03-22_14-11-15](https://user-images.githubusercontent.com/12860860/111994887-9a5a0980-8b18-11eb-881c-73227746bf3c.png)
