### ISSUE TITLE
Error after PC resets

### ISSUE THREAD

**Issue by bsstash** [fredemmott/StreamDeck-AudioSwitcher#24]
After every PC(Windows 10) reset, I get an error icon on the deck for both Toggle Audio device and Mute Mic commands. Other commands are working and no hardware issues.  No updates happen during the reset and Streamdeck.exe has full permissions.  When I click the icons in the Streamdeck app to edit, Streamdeck doesn't show the drop down menus or settings for the commands. Only a delete and re-install brings them back to function.
I've attached the two most recent logs, nothing stood out to me, but I have very knowledge of process. 
[StreamDeck log 1.txt](https://github.com/fredemmott/StreamDeck-AudioSwitcher/files/5211443/StreamDeck.log.1.txt)
[StreamDeck log 2.txt](https://github.com/fredemmott/StreamDeck-AudioSwitcher/files/5211445/StreamDeck.log.2.txt)

**Comment by Jokod** [comment]
Hello,

I confirm the problem, I have exactly the same problem.

It's a shame, the extension is essential in my eyes.
