### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by getify** [fredemmott/StreamDeck-AudioSwitcher#25]
**Describe the bug**
I had been using this plugin in streamdeck for the last several months with no issues. I don't think I had any system updates (possible, but I didn't notice), but now it no longer works. I've uninstalled and reinstalled, restarted, restarted SD, etc. All I get is a yellow warning icon overlayed on the button whenever I try to push it to switch from speaker to headphones.

I also have SoundSwitch app installed on my system, and it's able to switch these two just fine. And your plugin never had any conflicts with SoundSwitch before. But even if I close SoundSwitch, I get the same failure with your plugin.

**Expected behavior**
It always used to just toggle my speaker to headphones, or vice versa, which also updated what SoundSwitch saw. Now, only SoundSwitch works and this plugin doesn't.

**Debugging Information**

**Log File**
```
14:16:52.994                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_0b565748c80c245c6dacbb627626632b>::operator ()(): The plugin 'Audio Output' crashed with code 1:-1073741819
14:16:52.994                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_0b565748c80c245c6dacbb627626632b>::operator ()(): Restarting plugin 'Audio Output'
14:16:53.102                     StreamDeck                        ESDCustomPluginCommunication::onMessageReceived(): Plugin 9A4FB567F570EB0599779C432B47C7AE is now connected
14:17:20.844                     StreamDeck                        ESDActionsGridViewModel::onKeyPressed():        Key 3 pressed: com.fredemmott.audiooutputswitch.toggle
14:17:20.970                     StreamDeck                        ESDActionsGridViewModel::onKeyReleased():       Key 3 released: com.fredemmott.audiooutputswitch.toggle
14:17:34.654                     StreamDeck                        ESDActionsGridViewModel::onKeyPressed():        Key 3 pressed: com.fredemmott.audiooutputswitch.toggle
14:17:34.776                     StreamDeck                        ESDActionsGridViewModel::onKeyReleased():       Key 3 released: com.fredemmott.audiooutputswitch.toggle
```

** Operating System **

Windows 10 Home, Version 2004, Build 19041.630

**Additional context**

**Comment by fredemmott** [comment]
Try removing and re-adding the buttons; some windows update recently changed the device IDs. Additionally, check your antivirus settings. If you need further help, please open a helpk request at https://github.com/fredemmott/StreamDeck-AudioSwitcher/discussions
