### ISSUE TITLE
Can't Toggle Audio Device in Multi Action

### ISSUE THREAD

**Issue by jpooley-hearst** [fredemmott/StreamDeck-AudioSwitcher#29]
**Is your feature request related to a problem? Please describe.**
Toggle Audio Device is not enabled for Multi Action use

**Describe the solution you'd like**
Enable Multi Actions on Toggle Audio Device
--Or--
You could provide an action to Toggle Both Audio Devices (output & input) so using a Multi Action is not necessary

**Describe alternatives you've considered**
Could use two separate Mutli Actions rather than having it be a toggle but that's not ideal

**Comment by fredemmott** [comment]
This is currently intentionally not done, as it gets you to a not-easily-fixable inconsistent state if a multi-action partially succeeds; you can change this if you want by editing the `manifest.json` in your plugin installation directory.

The usual approach here is to use a multi-action switch, which effectively makes a single streamdeck button act as a toggle between two multi actions, and means if you get to an inconsistent state, you just push the button again to fix it

**Comment by fredemmott** [comment]
Say you have 3 devices, A B C. You have two desired states:

State 1: A for input and output
State 2: B for input, C for output

If you're in state 1, C is disconnected, and you push the button, you end up with B for output, A for input.

You don't want this, so you plug in the device, and push the button again

You now have A for output, C for input. You push again, you're back to B output, A for input. You can't get back to a desired state without going through windows settings.

**Comment by jpooley-hearst** [comment]
I didn't realize they added a Multi Action Switch, and the manifest.json trick may work for the VLC actions that I haven't been able to add to a Multi Action previously. Thanks very much!!
