### ISSUE TITLE
Plugin doesn't work in Admin Mode

### ISSUE THREAD

**Issue by tylerhennessy** [fredemmott/StreamDeck-AudioSwitcher#31]
I need to run streamdeck in admin mode for some of my other shortcuts(mainly Visual Studio), but when I launch it in admin mode, all of the AudioSwitcher buttons break.  When I go into streamdeck and try and update the input/output buttons, it doesn't even display the audio options.  I can only change the icon and title.

**Comment by fredemmott** [comment]
I'm not planning on working on this, but would be interested in any pull requests addressing this if possible.

**Comment by fredemmott** [comment]
Closing as this is unlikely to be worked on; I would greatly appreciate pull requests
