### ISSUE TITLE
Firefox not switching sound output

### ISSUE THREAD

**Issue by DirkTeulings** [fredemmott/StreamDeck-AudioSwitcher#33]
**Describe the bug**
When using "one-button-per-device" firefox'es output will not change.
Overy other program will but firefox won't.

**To Reproduce**
1. Open firefox
2. Go to youtube
3. Play video/sound
4. Switch sound

**Expected behavior**
When pressing a "one-button-per-device" sound will play via this device

**Log File**
[StreamDeck0.log](https://github.com/fredemmott/StreamDeck-AudioSwitcher/files/6048826/StreamDeck0.log)

** Operating System **
Windows 10 Pro 64 Bit

**Additional context**
Firefox version 86.0

Note: Chrome does switch from output.
This all maybe Firefox related bugs, but maybe this is also broken for you.

There is another program around called: Sound Switch - https://soundswitch.aaflalo.me/?utm_source=application#
This one is able to switch the output of Firefox. 
But that does not work nicely

**Comment by fredemmott** [comment]
Check windows audio settings -> advanced, while Firefox is open, and make sure Firefox is set to default; otherwise, this probably needs reporting with Firefox (assuming you have the same problem when changing default device from mmsys.cpl)
