### ISSUE TITLE
Support for switching an application audio output

### ISSUE THREAD

**Issue by RoadRunnerAB** [fredemmott/StreamDeck-AudioSwitcher#34]
Since Windows 10 1803 there is the "App volume and device preference" option in the settings menu. This allows for setting the output device on a per app basis https://winaero.com/audio-output-device-apps-individually-windows-10/.

Analog to switching a output device of the system there are usecases where switching an output of a dedicated app via the Stream Deck would be very usefull.

One possible usecase is: For streaming or lecture a selection of apps is routed via virtual audio cables for better audio control to OBS. For monitoring the composed sound of OBS could be output via the monitor plugin to the Default audio device. When the stream or lecture is done the user needs to manually change back the apps to the default device, if OBS shall be closed.
Here AudioSwitcher could allow much easier switches between setups. 

I searched a bit on the net and found https://superuser.com/questions/1348988/set-audio-endpoint-devices-application-specific-programmatically as a starting point. There, the Core Audio API https://docs.microsoft.com/en-us/windows/win32/coreaudio/core-audio-apis-in-windows-vista is mentioned to be the API to control this feature in windows.

Because the PlugIn is named AudioSwitcher I would suggest to inlcude this feature in this PlugIn.

**Comment by fredemmott** [comment]
Closing - this is meant to be supported by https://github.com/BarRaider/streamdeck-wintools

Locking: this is the same as #23 - if there's something missing, it'll be best to re-open the first one and centralize discussion.
