### ISSUE TITLE
Bug: Input Profile Resetting on Toggling Output

### ISSUE THREAD

**Issue by kalanihelekunihi** [fredemmott/StreamDeck-AudioSwitcher#4]
**Description:** 
When using 2 Toggle Audio Device buttons on a Stream Deck - one for Input and the other for Output - setting the output device alters the state of the input button without changing the actual audio device. The inverse where one presses the input button, the output button remains unaffected.

**Reproduction Steps:** 
When using Toggle Audio Device, set up 2 buttons

For the first, choose a Primary and Secondary output device, and assign as Output Default.
Example: Monitor and Headphones
For the second, choose a Primary and Secondary input device, and assign as Input Default.
Example: Microphone and Headphones Microphone

When one presses the first button (output), the input will also swap its state to Primary, along with a temporary yellow exclamation point image before returning to the expected image. However, the input will not change (presumably expected). This results in the button state and images are out of sync with the actual input.

When one presses the input button, the output button remains unaffected (intended behavior).

**Comment by fredemmott** [comment]
I'm sorry it took so long to respond; at some point last year, the GitHub notifications settings for several of my personal projects were changed - none of my actual work projects were affected, so I did not notice until mentioned on a new issue.

Will see if I can reproduce this in the next week or so (hopefully this weekend).

**Comment by fredemmott** [comment]
I think this was fixed by https://github.com/fredemmott/StreamDeck-AudioSwitcher/commit/f673365beee287dd178cb4225fe6ab8c15c1f1f3 , in 2.2 from august last year
