### ISSUE TITLE
Plugin fails to work until I restart StreamDeck

### ISSUE THREAD

**Issue by rcarmo** [fredemmott/StreamDeck-AudioSwitcher#40]
**Describe the bug**

Plugin fails to work until I restart StreamDeck

**To Reproduce**

1. Boot Mac
2. Try to use action to switch audio device
3. Notice it fails
4. Restart StreamDeck
5. Try to use action again
6. It works

**Expected behavior**

It should work on every initial app load. However, it _consistently_ only works when I restart StreamDeck, even though StreamDeck launches automatically on login and everything else works fine.

**Debugging Information**

- screenshot of the expanded Debug Information section of property inspector
- how recent is "Last State Change" in that section? - is it seconds, minutes, or hours?
- how frequently the 'last state change' is changing, if at all?

(Not sure how to get the above on the Mac as there doesn't seem to be any way to get those)

**Log File**

[StreamDeck0.log](https://github.com/fredemmott/StreamDeck-AudioSwitcher/files/6446402/StreamDeck0.log)

** Operating System **

Mac OS Big Sur 11.3.1

**Additional context**

I use the plugin inside multi-actions, like so:

<img width="952" alt="Screen Shot 2021-05-08 at 20 08 46" src="https://user-images.githubusercontent.com/392683/117550625-44461480-b039-11eb-98e8-3c1e9493f181.png">
<img width="952" alt="Screen Shot 2021-05-08 at 20 08 49" src="https://user-images.githubusercontent.com/392683/117550627-46a86e80-b039-11eb-8bbd-acbda4dca339.png">

**Comment by Sneltrain** [comment]
I have the same problem on Windows. After booting my pc

**Comment by fredemmott** [comment]
I think this is about software startup order; I normally don't need to do this, but have done when I only turned on my USB sound card *after* the streamdeck software had started.

**Comment by rcarmo** [comment]
The USB sound card is active before the desktop starts.

**Comment by ldecarufel** [comment]
I have the exact same problem on Windows 10 Home.
The plugin stops working after I reboot.  The "Set Audio Device" buttons always display a yellow exclamation point and the properties are empty.
Everything works fine avec quitting and restarting StreamDeck.

**Comment by Sneltrain** [comment]
Sooo I didn't stumble upon this issue for a while now and I wanted to share my thoughts...
I've reinstalled everything (including Windows 10) since I've got new hardware and I've installed Stream Deck on my C drive, which is a m.2 SSD. I don't remember if Stream Deck was on my C drive before but maybe that's something to look into. What I do know is that my user account (the only one on this pc) does not have a password anymore, so Windows directly logs into it when booting. Maybe this has some impact on how Stream Deck / this plugin loads and detects audio devices.

I hope this helps.

**Comment by fredemmott** [comment]
Assuming this is #73 ; while the device may be plugged in on boot, that doesn't mean it'll be initialized and ready to go. Even if it's not that, handling replug should lead to pressing it making it reinitalize and stop a restart being needed.
