### ISSUE TITLE
Add option

### ISSUE THREAD

**Issue by AceofCookies** [fredemmott/StreamDeck-AudioSwitcher#44]
Hello!

I don't currently see a way to switch both communications device and default device at the same time, consequently it works perfectly in for example discord and OBS, which uses default communications device , but will not work for Viber calling.

Thanks!

**Comment by fredemmott** [comment]
Yes; what should the button do if changing default succeeds but changing communications?
- what should it display?
- what should pressing it a second time do?
- what if the default is primary and commnunications is secondary when the button is pressed? make them both be the same, or swap them?
- is it possible to get into a state that is unwanted but can't be fixed by pressing the button again?
- will it be obvious to a user what's going on in those situations?

The multi-action switch approach (using the 'set' action rather than 'toggle') provides clear answers to those, and is built-in to the elgato software.

**Comment by fredemmott** [comment]
<img width="267" alt="image" src="https://user-images.githubusercontent.com/360927/119858538-2e11d280-beda-11eb-9ec0-c1da99b82809.png">

<img width="519" alt="image" src="https://user-images.githubusercontent.com/360927/119858707-56013600-beda-11eb-935a-44c251fe6361.png">

<img width="524" alt="image" src="https://user-images.githubusercontent.com/360927/119858774-64e7e880-beda-11eb-8223-ee21b18c5fd8.png">


This approach also lets you easily switch microphone at the same time as the speakers.

**Comment by AceofCookies** [comment]
> Yes; what should the button do if changing default succeeds but changing communications?

I feel like this is such an unlikely scenario that we don't really need to consider it 😄 

> * what should it display?

The default device, I suppose.

> * what should pressing it a second time do?

Toggle to the non-default device.

> * what if the default is primary and commnunications is secondary when the button is pressed? make them both be the same, or swap them?

When the "Both" option is selected, it probably makes sense to just make the default communication device follow the default device, i.e. always make it the same.

If the default device is device A and the default communication device is device B, pressing the toggle button would set both devices to device B, since it would only consider the existing state of the default device. I think this would fit most people's use case.

> * is it possible to get into a state that is unwanted but can't be fixed by pressing the button again?

Not with the logic I suggested above.

> * will it be obvious to a user what's going on in those situations?

After watching the sound panel and pressing the button a couple of times, it should be pretty clear I think.

> The multi-action switch approach (using the 'set' action rather than 'toggle') provides clear answers to those, and is built-in to the elgato software.

The only issue is that I would need 2 or more buttons for this, rather than having 1 toggle button. (At least that is my current understanding.)

**Comment by fredemmott** [comment]
> I feel like this is such an unlikely scenario

It's not, especially with removable devices

> we don't really need to consider it 😄

Has been considered on multiple past issues here :)

> The only issue is that I would need 2 or more buttons for this, rather than having 1 toggle button. (At least that is my current understanding.)

If using 'multi action', yes, but with 'multi action switch', no - a multi action switch effectively toggles between two multi-actions.

**Comment by AceofCookies** [comment]
> It's not, especially with removable devices

How would un-plugging a device cause toggling default device to succeed but default communications device to fail? 🤔 

> If using 'multi action', yes, but with 'multi action switch', no - a multi action switch effectively toggles between two multi-actions.

Aha, I've never heard of multi action switches. I'll look into that, thanks :)
