### ISSUE TITLE
Work with Boom 3D on macOS

### ISSUE THREAD

**Issue by pedropombeiro** [fredemmott/StreamDeck-AudioSwitcher#46]
**Is your feature request related to a problem? Please describe.**

Until recently I was using https://github.com/deweller/switchaudio-osx in a bash script to switch audio sources. This works well with [Boom 3D](https://www.globaldelight.com/boom/) (which is a virtual sound input/output source to add effects/EQ). Although StreamDeck-AudioSwitcher seems to work fine, it doesn't seem to switch audio sources in quite the same way as switchaudio-osx, because the audio output is not reflected in Boom 3D as when it is done by switchaudio-osx.

**Describe the solution you'd like**

I was wondering if we could use the [same macOS APIs as switchaudio-osx](https://github.com/deweller/switchaudio-osx/blob/master/audio_switch.c#L458).

**Describe alternatives you've considered**

**Additional context**

<img width="348" alt="2021-06-05 at 11 12" src="https://user-images.githubusercontent.com/138074/120886568-f0562d80-c5ee-11eb-9be5-cf91a882623d.png">

**Comment by fredemmott** [comment]
Unfortunately that API is deprecated; this project (via audiodevicelib) is using the recommended replacements (https://developer.apple.com/library/archive/technotes/tn2223/_index.html)

“Sources” - do you specifically mean input devices (i.e microphones), or destinations/output devices? If the latter, the issue could be that this only sets the default device, not the system device.

**Comment by fredemmott** [comment]
https://github.com/fredemmott/AudioDeviceLib/blob/master/src/AudioDevicesMacOS.cpp#L170 Implementation is there - there’s also some cli examples that might be useful for testing

**Comment by fredemmott** [comment]
Actually, those can easily be changed independently in apple’s audio midi setup; if you could experiment with that and identify which changes are reflected in Boom3D, that’d make next steps clearer

**Comment by pedropombeiro** [comment]
> Actually, those can easily be changed independently in apple’s audio midi setup; if you could experiment with that and identify which changes are reflected in Boom3D, that’d make next steps clearer

This is what my MIDI setup looks like:

<img width="627" alt="2021-06-05 at 15 19" src="https://user-images.githubusercontent.com/138074/120893079-88fda500-c611-11eb-9ace-20e9c6962e60.png">

I think what Boom 3D does is intercept changes to audio output to `<target>` to do the following:
- set its internal output to `<target>`
- reset itself as the output in macOS MIDI setup

Also, I found that making the change in the MIDI setup works as expected:

<img width="640" alt="2021-06-05 at 15 24" src="https://user-images.githubusercontent.com/138074/120893203-48525b80-c612-11eb-9cdf-69c28326d99a.png">

**Comment by pedropombeiro** [comment]
Oh wait, I just realized that if I re-open Boom 3D from the menu bar, it reflects the updated source. So it seems that the only difference with the used method is that the UI doesn't update back and forth in real time, but that's not a meaningful issue. I'll close this issue then.

Thanks for the quick response!
