### ISSUE TITLE
There seems to be an issue with the plugin and the recently released Stream Deck 5.0 update

### ISSUE THREAD

**Issue by smileytech** [fredemmott/StreamDeck-AudioSwitcher#48]
**Describe the bug**
I noticed that the plug-in's actions stopped working after I upgraded to Stream Deck 5.x

**To Reproduce**
1. Install the latest version of Stream Deck
2. The plugin's assigned buttons stop working and I can no longer see the usual properties for the plugin's actions (Direction, Device, and Role).  The only properties I see is the default Title one.
3. Uninstalling Stream Deck 5.x and reinstalling 4.9.x resolved the issue so I'm assuming it's a compatibility issue with the new 5.x version

**Log File**
I don't see any specific logs for the plugin, however when I looked in one of the StreamDeckx.log files, I see this in case it's helpful:

21:47:00.036                     StreamDeck                        ESDPreferenceTabGeneral::DeviceStateChangedNotification(): Dev FW ver: 1.0.191203, Embed FW ver: 1.0.191203
21:47:00.036                     StreamDeck                        ESDPreferenceTabGeneral::DeviceStateChangedNotification(): show update fw button: no
21:47:00.036                     StreamDeck                        ESDPreferenceTabGeneral::DeviceStateChangedNotification(): Serial No: <omitted>
21:47:00.037                     StreamDeck                        ESDActionRegistry::CreateNewAction():           Trying to create an action from an unknown type com.fredemmott.audiooutputswitch.set
21:47:00.037                     StreamDeck                        ESDActionRegistry::CreateNewAction():           Trying to create an action from an unknown type com.fredemmott.audiooutputswitch.set
21:47:00.102                     StreamDeck                        ESDCustomPluginCommunication::onMessageReceived(): Plugin FC518EB5F86D03F59F923923106E408B is now connected
21:47:00.562                     StreamDeck                        ESDCustomPluginCommunication::onMessageReceived(): Plugin 0E18A7B6763FE23A9A5273408715B267 is now connected
21:47:01.066                     StreamDeck                        ESDCustomPluginCommunication::onMessageReceived(): Plugin A13A2899C85B9FAA117AD3001E7559D9 is now connected
21:47:01.200                     StreamDeck                        ESDCustomPluginCommunication::onMessageReceived(): Plugin A652848E3C6DB07D4A8C19E8E98DA536 is now connected
21:47:01.399                     StreamDeck                        ESDCustomPluginCommunication::onMessageReceived(): Plugin EEE9D841B4AC1489D7C9CCBF76206870 is now connected
21:47:03.409                     StreamDeck                        EGQTSWUpdateDialog::checkForUpdate():           Check for update 2: https://gc-updates.elgato.com/windows/sd-update/final/app-version-check.json
21:47:03.409                     StreamDeck                        EGQTSWUpdateDownloader::startDownload():        Download task name: Update File, file URL: https://gc-updates.elgato.com/windows/sd-update/final/app-version-check.json
21:47:03.528                     StreamDeck                        EGQTSWUpdateDialog::shouldUpdate():             current SW Ver: 5.0.1.14252, remote SW Ver: 5.0.1.14252
21:47:03.528                     StreamDeck                        EGQTSWUpdateDialog::handleUpdateFileDownloaded(): No update available
21:47:04.986                     StreamDeck                        ESDAppStoreManager::UpdateAppStorePlugins():    Check for Plugin Store updates
21:47:04.987                     StreamDeck                        ESDAppStoreManager::UpdateAppStoreIconPacks():  Check for icon pack Store updates
21:47:15.310                     StreamDeck                        MainWindow::event():                            Wake up keypad(s).
21:47:17.175                     StreamDeck                        ESDAppStoreManager::UpdateAppStorePlugins():    Check for Plugin Store updates
21:47:17.175                     StreamDeck                        ESDAppStoreManager::UpdateAppStoreIconPacks():  Check for icon pack Store updates
21:47:35.040                     StreamDeck                        ESDAppStoreManager::onPluginDownloadQueryFinished(): Could not save plugin to disk C:\Users\russe\AppData\Local\Temp\com.fredemmott.audiooutputswitch.streamDeckPlugin
21:47:50.171                     StreamDeck                        MainWindow::event():                            Wake up keypad(s).
21:49:17.563                     StreamDeck                        MainWindow::event():                            Wake up keypad(s).

** Operating System **

Windows 10 Professional, 64-bit

**Additional context**
While trying to get the plugin to work under 5.x, I tried to uninstall it and reinstall it from the new plugin store.  When I did this, the store interface indicated it was installing the plugin, but in reality, nothing happened (closing and reopening the store once again showed the plugin as being currently uninstalled).  It was at this point I tried to uninstall Stream Deck 5.x and reinstall an older 4.9.x version, which let me reinstall the plugin via the release package on GitHub and restore functionality.

**Comment by aanders50** [comment]
@fredemmott Do you know if you will be updating the addon to StreamDeck 5.0 or leaving it on 4.0? Just trying to see if I should downgrade or look at another solution.

Thanks!
