### ISSUE TITLE
Toggle/Route individual sources

### ISSUE THREAD

**Issue by Newyears1978** [fredemmott/StreamDeck-AudioSwitcher#52]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, just renders it unusable for what I need.

**Describe the solution you'd like**
The toggle function is PERFECT however since I use a Wave 3 microphone I have all my sources individually routed in sytem sound settings. So for instance I have my browser routed to a specific output. So toggling the DEFAULT output doesn't do anything. Possible to update this so it shows all sources including programs like browser, spotify, etc.

**Describe alternatives you've considered**
Cannot find an alternative.

**Comment by fredemmott** [comment]
Sorry, this plugin only works with windows settings, and I don't have any wave devices. You probably want to reach out to elgato to request this.
