### ISSUE TITLE
Plugin Crashes When Device Removed

### ISSUE THREAD

**Issue by Stumpyz** [fredemmott/StreamDeck-AudioSwitcher#71]
**Describe the bug**
Whenever I unplug my headset, the plugin crashes. This also happens more recently with the mic mute plugin, but mainly with this plugin.

**To Reproduce**
1. Have the latest plugin installed
2. Set one of the devices to switch between to be a headset you can unplug
3. Unplug the headset
4. See the crash

**Expected behavior**
The plugin will not crash if it can no longer find the audio device.

**Debugging Information**
I don't currently have VS installed on this PC, but if the info is necessary just ping me and I'll get that going.

**Log File**
The only logs I found were for the mic mute plugin, which didn't contain anything other than when I've needed to update a device, so it wouldn't help.

** Operating System **
Windows 10 Pro, 20H2 update

**Additional context**
This has been happening for a bit, which I assumed was just some shenanigans from my setup until it started happening with the mic mute plugin as well. I have a feeling that either there's a library being accessed that doesn't know how to handle devices disappearing, or that the plugins handle devices the same way, causing the same crash. Let me know if there's any specific testing that needs to be done on my setup to make this easier.

**Comment by fredemmott** [comment]
> until it started happening with the mic mute plugin as well

I think this has been a problem forever (but something changed on the Elgato side which made it more obvious) - can you try RelWithDebInfo-StreamDeckPlugin from https://github.com/fredemmott/StreamDeck-AudioMute/actions/runs/1698347624 ?

If that fixes it, it should be a similarly simple fix for this plugin

**Comment by Stumpyz** [comment]
Just tried it a few different ways, still getting the crash. I uninstalled the crashing plugins and installed the RelWithDebInfo-StreamDeckPlugin - same issue. Log is attached, but it looks like it's just registering whenever I make the icon over again.
[com.fredemmott.micmutetoggle0.log](https://github.com/fredemmott/StreamDeck-AudioSwitcher/files/7908288/com.fredemmott.micmutetoggle0.log)

**Comment by fredemmott** [comment]
A minidump would be useful - https://github.com/fredemmott/StreamDeck-AudioMute/discussions/40#discussioncomment-1970492 has some comments on how to enable that without any developer tools

> I don't currently have VS installed on this PC, but if the info is necessary just ping me and I'll get that going.

This would be very helpful, but if you're able to get a minidump, that'll also work; a lighter weight alternative to VS would be to grab https://www.microsoft.com/en-us/p/windbg-preview/9pgjgd53tn86?activetab=pivot:overviewtab

**Comment by Stumpyz** [comment]
Got some minidumps for both this and the mic mute plugin, looks like I set my PC to make them previously and totally forgot. Uploading a total of seven dumps in a ZIP.
[CrashDumps.zip](https://github.com/fredemmott/StreamDeck-AudioSwitcher/files/7909033/CrashDumps.zip)

**Comment by fredemmott** [comment]
Very similar here:

```
STACK_TEXT:  
000000f5`bafff1b0 00007fff`6d463679     : 00000000`00000000 0000ac53`598e3323 00000204`28e1e9f0 00000000`00000000 : sdaudioswitch+0x2c9b3
000000f5`bafff250 00007fff`6d44ae62     : 00000000`00000000 00000000`00000000 00000204`28e3c094 000000f5`bafff5b8 : MMDevAPI!?OnDefaultDeviceChangedForPolicy@CDeviceEnumerator@@UEAAJW4__MIDL___MIDL_itf_mmdeviceapi_0000_0000_0001@@W4__MIDL___MIDL_itf_mmdeviceapip_0000_0000_0001@@PEBG@Z+0xf9
000000f5`bafff2a0 00007fff`6d424d94     : 000000f5`bafff5b8 00000000`00000000 00000204`28e259b0 00000000`00000000 : MMDevAPI!CLocalEndpointEnumerator::OnMediaNotification+0xf342
000000f5`bafff340 00007fff`78c00bf9     : 00000204`28e259b0 00000204`00000002 00000204`28e3c060 00000204`28e25aa0 : MMDevAPI!CMediaNotifications::OnMediaNotificationWorkerHandler+0x1f4
000000f5`bafff3f0 00007fff`78be315a     : 00000204`28df0af8 00000204`28e2fbe0 00000000`00000000 00000204`28df0b68 : ntdll!TppSimplepExecuteCallback+0x99
000000f5`bafff440 00007fff`770c7034     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!TppWorkerThread+0x68a
000000f5`bafff740 00007fff`78be2651     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
000000f5`bafff770 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21
```

**Comment by fredemmott** [comment]
Filed #73 for general category of these
