### ISSUE TITLE
2 "the same" output devices. Only one set works. Reboot defaults to not-working pair

### ISSUE THREAD

**Issue by Rawh** [fredemmott/StreamDeck-AudioSwitcher#72]
**Describe the bug**

When rebooting / starting the pc and pressing the button in Streamdeck, nothing happens. When looking at the config at glance everything is setup correctly, however when looking closer I can see my headphones and speakers twice in the list. By default the not-working pair are selected. I can fix it manually but when rebooting it has the wrong ones again.

**To Reproduce**

1. Start Windows 11
2. Wait till Streamdeck is started
3. Open YT, start any song
4. Sound is now on headphones (by default)
5. Click the button on the streamdeck
6. Button of streamdeck changes to speakers
7. Sound still on headphone
8. Open config. See two speakers and headphones in the list. Set it up to use the others in the list.
9. Press button again, sound now changes to other output.

Expected behavior

1. I would expect to only see the correct output's in the selection screen. Not the wrong one. 
2. After fixing it and rebooting I would expect it to continue working, since I fixed it, but it doesn't.

Debugging Information
- Windows 11 version 21H2
- OS Build 22000.493
- Streamdeck version 5.2.0.14948
- Firmware version: 1.00.012
- Audio Switcher version 3.0 - 2/16/2021

Some screenshots:
![image](https://user-images.githubusercontent.com/10486655/153581555-e63a8793-877e-4c1e-9e70-00856f1fadcf.png)
![image](https://user-images.githubusercontent.com/10486655/153581599-c905f63f-9e40-4d01-a521-805f311021c7.png)

**Comment by fredemmott** [comment]
Closing for #74 with cause there
