### ISSUE TITLE
Provide workaround for buggy windows drivers with incorrect device ID behavior

### ISSUE THREAD

**Issue by fredemmott** [fredemmott/StreamDeck-AudioSwitcher#74]
> The endpoint ID string of a device changes if the user upgrades the device driver, or if the user uninstalls the device, and installs it again. However, the endpoint ID string remains unchanged across system restarts, and the endpoint ID string of a USB audio device remains unchanged if the user unplugs the device and plugs it back in.

https://docs.microsoft.com/en-us/windows/win32/coreaudio/endpoint-id-strings

Some drivers are definitely changing the device ID on reboot or replug, despite this being explicitly incorrect behavior.

One way to add this would be an off-by-default option to match by name instead of device ID. This should be off-by-default as it will introduce issues on systems with multiple devices of the same kind and drivers without this bug.

**Comment by anotherlab** [comment]
I'm seeing this problem on Windows 11. After every Windows update, I have to go in and reselect the audio devices.

**Comment by garv3** [comment]
Yeah, I am facing this issue as well.
From time to time the key stops working and the ausio device is listed twice in the settings, so I have to select the other one.

**Comment by anotherlab** [comment]
I would like the match by name as an option.  I switch back and forth between my speakers (connected to the onboard audio) and my headphones (connected to a USB DAC).  I rename the devices to make them easier to select.  If there was an option to match by name, those names would be unique on my system.

**Comment by garv3** [comment]
Is the project dead?

**Comment by fredemmott** [comment]
I still use it, and am likely to fix things if something changes that makes it stop working on devices with drivers that use IDs correctly. Other than that, it's a hobby project, and not one I'm currently working on. I'd be happy to review pull requests, and if merged, publish new releases.

**Comment by fredemmott** [comment]
https://github.com/fredemmott/StreamDeck-AudioSwitcher/releases/tag/v3.1-beta2 adds a 'fuzzy' matching option, however it does require an exact match on the device name as reported by Windows/MacOS:

There's still a potential problem on Windows though: Windows automatically renames USB sound cards if they've been plugged into multiple ports - for example:

![image](https://user-images.githubusercontent.com/360927/179383361-e25dc546-7472-441e-a477-997876ab1e90.png)

The "6-  " is part of Window's name for the device.

If you're getting numbers in the names like that, the option won't help (yet), but if you're not, this should be what you need.

I'd appreciate it if y'all could:

👍-react if this fixes things for you
👎-react if it doesn't

If it doesn't, it would also be good to open a terminal/command prompt, run 'list-devices,exe' (or without the .exe on macos) from the demo zip on https://github.com/fredemmott/AudioDeviceLib/releases/tag/v2.1.0 , and share the results via gist.github.com
