### ISSUE TITLE
Mac: Toggle device doesn't work when playing audio (through Chrome)

### ISSUE THREAD

**Issue by petercv** [fredemmott/StreamDeck-AudioSwitcher#79]
**Describe the bug**
I've configured the plug-in to toggle between 2 audio devices on my Mac. This works great in general, however when I'm actively playing audio (e.g. in a Meet, or playing a YouTube video) and try to switch the audio device it doesn't work. When I stop the video *and* close the tab it works again. 

**To Reproduce**
1. Go to  'YouTube'
2. Start playing video.
3. Toggle audio device.
4. Doesn't work.

** Operating System **
macOS Mojave

**Additional context**
I can switch audio devices using the speaker button in the macOS menu bar when active content is playing.

**Comment by fredemmott** [comment]
Sorry, I'm using Apple's only documented interfaces for changing the audio device; Apple have the ability to fix this, I don't.
