### ISSUE TITLE
Feature request: Set spatial sound option

### ISSUE THREAD

**Issue by mcbexx** [fredemmott/StreamDeck-AudioSwitcher#8]
Windows 10 offers different spatial sound options (Windows Sonic (free, included with Windows 10, Dolby Access ($, Windows Store), DTS (free, Windows Store)). I imagine being able to set the spatial sound model along with selecting the audio source would be really helpful.

**Comment by fredemmott** [comment]
Microsoft do not appear to offer a supported way to do this - https://docs.microsoft.com/en-us/windows/win32/api/spatialaudioclient/nn-spatialaudioclient-ispatialaudioobjectrenderstream seems a the most relevant place, but I'm not seeing anything for changing the system-level settings nearby or in IMMDeviceApi or IPolicyConfig

Also, I'm sorry it took so long to respond; at some point last year, the GitHub notifications settings for several of my personal projects were changed - none of my actual work projects were affected, so I did not notice until mentioned on a new issue.
