### ISSUE TITLE
Update OBS source

### ISSUE THREAD

**Issue by FazuBattlecaster** [fredemmott/StreamDeck-AudioSwitcher#80]
Currently the mute / unmute works fine and reflects on the stream deck, however, would it be possible for it to update the source inside of OBS Studio as well?

![image](https://user-images.githubusercontent.com/83257029/177206082-06290426-aa62-4d9d-b0de-452af25d98da.png)

**Comment by fredemmott** [comment]
This is supported by the remote control or obs tools plugins.

**Comment by FazuBattlecaster** [comment]
Perfect.  Thank you.
