### ISSUE TITLE
Add the option to change the Role Both together ?

### ISSUE THREAD

**Issue by marcel255** [fredemmott/StreamDeck-AudioSwitcher#86]
Hi,
Can You Please Add a Button for Change both together also default communication device and default device ?

Best regards

**Comment by fredemmott** [comment]
I won't be adding this; use the streamdeck's multi-action switch feature.

**Comment by marcel255** [comment]
@fredemmott 
> I won't be adding this; use the streamdeck's multi-action switch feature.

I would like to, but that doesn't work. I can only use "Set Audio Device" not "Toggle Audio Device"

**Comment by fredemmott** [comment]
Use multi action **switch** with set device on both sides of the multi action switch. A multi action switch itself provides toggle functionality.
