### ISSUE TITLE
Audio Switcher Streamdeck plugin change default and communications with one action.

### ISSUE THREAD

**Issue by LiveWithMadness** [fredemmott/StreamDeck-AudioSwitcher#87]
Hi, sorry for posting this on the wrong github. I actually don't know how I ended up messing chrome tabs. Anyway, I repost the message here with further information.

As suggested by developer, multi-action from Elgato's software doesn't work properly. It's kind of a "hit or miss" thing: Once you trigger the Action 1 (to set device B), it works. But when you try to trigger Action 2 (to set back device A) it just doesn't trigger. And viceversa. Besides, with multi-actions you actually lose the visual feedback of what device is being currently selected.

This issue is not urgent, but it would make a really nice feature to be able to select both options at the same time (Setting Default device and Communications device).

Thanks in advance!

Original post:

"I've been struggling to use this Streamdeck plugin (Audio Switcher) because it doesn't allow the Default Audio device at the same time that it changes the communications device. This is quite annoying because, e.g., you're playing games with friends over Discord and want to switch your whole audio to be outputted through headset, instead of speakers. You should use 2 buttons to do that as you need to change the default device (for it to affect the game) and then the communications device (for it to affect Discord).

If it makes things easier, before using this plugin, I used an executable (AudioSwitcher.exe) that allowed me to shortcut these actions on specific keybindings. Besides, this program offered an option to make it change both (default and communications devices) outputs with one shortcut. I'll add some screenshots at the end of this post in case I'm not making myself clear.

Could this be added to the Streamdeck plugin?

Thank you in advance."
![audioswitcher-settings](https://user-images.githubusercontent.com/99535862/196727577-0e119a17-c3c6-4c50-92ba-fcde3699a09e.png)

**Comment by LiveWithMadness** [comment]
On this post I was actually saying that Multi-Action feature isn't working properly, so unfortunately this is not a fix.

**Comment by fredemmott** [comment]
Ah, you are actually using multi action *switch* not multi action? Then the issue is why “set audio device” is not working for you.

> the visual feedback of what device is being currently selected.

There isn’t a clean and clear way to support this; even if both roles were an option, this would not be a feature, which is a large part of why I don’t want to add it.

**Comment by fredemmott** [comment]
If it’s a problem specifically with “set audio device”, can you open a Q&A discussion thread?

If it’s a broader problem with multi action switch, you need elgato support

**Comment by LiveWithMadness** [comment]
Ok, I'm just digging around the Q&A threads and what I understand is that you don't find a good enough way to display what device is selected for each role. Am I wrong?

If this is the main problem, I'd say that it's better to have the option of enabling both roles at the same time and just assume that they will be working. Because either way, if another program should change it, you just need to press the Streamdeck key again and it sets that device for both roles again, right? Maybe I'm oversimplifying, but I'm not that acknowledged on programming and what can be done, so apologies if I am.

I can gladly open a Q&A discussion with this idea to see if someone has another perspective. All other posts are relatively old now.

**Comment by fredemmott** [comment]
That would work, but would essentially be duplicating Elgato’s multi action switch functionality which isn’t a good use of time.
