### ISSUE TITLE
Fuzzy matching in 'Set Audio Device' doesn't work even if there is just a few characters difference

### ISSUE THREAD

**Issue by krislabs** [fredemmott/StreamDeck-AudioSwitcher#89]
**Describe the bug**
Windows has a dumb tendency to add new device drivers when a device is for example connected to other USB port or hub. It adds a number to the device name. Example:

- Headphones (Razer Nari Ultimate - Game)
- Headphones (2- Razer Nari Ultimate - Game)

Fuzzy matching won't select the second device instance if the first one was selected in Stream Deck button's settings.

**To Reproduce**
1. Create 'Set Audio Device' button.
2. Set 'Device'.
3. Set 'Device matching' to 'Fuzzy'.
4. Connect your selected audio device to another USB port or hub.
5. Check in 'Device Manager' if indeed Windows added a number to the device's name (enabling 'View' > 'Show hidden devices' might be necessary).
6. Select another audio device in Windows sound settings.
7. Use this newly created Stream Deck button to switch back to the reconnected device.
8. Yellow warning triangle appears on the button and audio device is not switched.

**Expected behavior**
Fuzzy matching should ignore these 3 characters difference and set desired device.

**Debugging Information**

**Log File**
none

**Operating System**
Windows 10 Home, 64-bit

**Additional context**
Maybe the fuzzy matching should select device using matching by whole words or have a simple percentage of matching characters hard coded such as 0.75.

**Comment by fti7** [comment]
Same here :-( 
@fredemmott can you please add another Option with e.g. String Match or better Regular Expressions? So Advanced Users can tweak this properly. Thank you

**Comment by cerahmed** [comment]
Hey there,

A little late to the issue, but I have been facing a similar issue and I was looking for a workaround.
As @fti7 suggested, I modified the code to allow for a regular expression matching. You can try it out on my forked repo: [here](https://github.com/cerahmed/StreamDeck-AudioSwitcher/releases).

In your case, you can keep the previous (unplugged) device selected, then select Regex matching and paste the following regular expression: `.*Razer Nari.*` .. and whenever Windows adds the odd digits, it will be ignored.

Let me know if that works for you.

P.S. I think regular expression is for niche users of the plugin, therefore I didn't create a pull request.

**Comment by fredemmott** [comment]
There's a test version here: https://nightly.link/fredemmott/StreamDeck-AudioSwitcher/actions/runs/7372082826/com.fredemmott.audiooutputswitch.streamDeckPlugin.zip - please let me know if it works for you.

**Comment by fredemmott** [comment]
Improved in e2d51f83c128789193eea4fdc292456d8bc75238

**Comment by fti7** [comment]
Doesnt seem to work. Installed plugin Version: 3.2.0.71

![image](https://github.com/fredemmott/StreamDeck-AudioSwitcher/assets/7014664/2b70e066-51a8-4456-be88-82a06147c099)

The previously selected Yellow marked Device at the Bottom disappeared, but the Blue marked one appeared, it should automagically switch to this one

**Comment by fredemmott** [comment]
https://nightly.link/fredemmott/StreamDeck-AudioSwitcher/actions/runs/7372492268/com.fredemmott.audiooutputswitch.streamDeckPlugin includes a bugfix

@fti7 the above includes a bugfix, but the behavior you're seeing is expected: the properties will always remember and show the *exact* device you selected, but if fuzzy matching is enabled, the button state and pressing/release will show/affect the fuzzily-matched device.

**Comment by fredemmott** [comment]
Reason being that if the original device isn't present and you turning fuzzy matching on, turning it off again should be 'undo' - it shouldn't have permanently reattached to the fuzzy device.
