### ISSUE TITLE
Option to set both default and communications device at the same time when switching

### ISSUE THREAD

**Issue by yapja** [fredemmott/StreamDeck-AudioSwitcher#9]

**Comment by AbbieGator** [comment]
Can we get this please? It would greatly help as Discord relies on the communication device but other programs rely on the default device so having both at once would be good. At the moment I have 2 SetAudioDevices in a multi action so that both work.

**Comment by smikutsky** [comment]
I came here to ask for the same feature. Can we pretty please have this?

**Comment by fredemmott** [comment]
I'll look at adding this as long they're going to the same device (which seems to be what you're asking for); I've had other requests for "set default device to X, communications device to Y", which is more complicated mostly for "what to display if one change succeeds and one fails?" - multiactions seem like the right solution

Also, I'm sorry it took so long to respond; at some point last year, the GitHub notifications settings for several of my personal projects were changed - none of my actual work projects were affected, so I did not notice until mentioned on a new issue.

**Comment by fredemmott** [comment]
Well... state display is still an issue; what should the streamdeck show if:
- it successfully sets both devices to your chosen one
- something else changes one of them

... I'm tempted to make that display the ! triangle.

**Comment by fredemmott** [comment]
This is equivalent to #2
