### ISSUE TITLE
Windows Volume mixer application output support

### ISSUE THREAD

**Issue by mitch-waters-iii** [fredemmott/StreamDeck-AudioSwitcher#90]
**Is your feature request related to a problem? Please describe.**
I use voicemeeter virtual cables to separate audio tracks when I record/stream. On windows (10 or 11), I can set the audio output for a particular application using the volume mixer, choosing the application (like Spotify) and changing the output from default to a virtual cable. I can then control the audio levels inside of OBS and split what goes to stream and/or recording. 

**Describe the solution you'd like**
I would love a way to change the audio output using a key in the stream deck. Set it to my virtual cable when I stream, set it back when I shut everything down for my stream.

I see this working by adding a new widget to the plugin - something like `Set Application Audio Device`. The configuration would take an input for application (hopefully this can be pulled from the `Apps` list on the volume mixer configuration), and then set the output the way that the existing `Set Audio Device` widget does.  Alternatively, this could be an enhancement to the existing widget, and it defaults to `All` or `Default` , and it would just behave as it does now. 

I'm not a C++ programmer (I mostly write in Java and python) but I'll try to find examples of doing this programmatically, and I'm even open to trying to patch something in on my own if you are open to PRs. 

**Describe alternatives you've considered**
I do this manually now. Spotify does not support a setting to change the output from within it's application, and this is a native Windows way to change an application's output. 

**Additional context**
Screenshot of the related settings in windows:
![Screenshot 2022-10-23 094002](https://user-images.githubusercontent.com/12472984/197404513-7c2983dc-6415-47b5-96f3-63cb27bc813d.png)

**Comment by fredemmott** [comment]
I believe this is supported by Barraider's wintools plugin; I don't intend to duplicate it here

**Comment by mitch-waters-iii** [comment]
good to know, thanks.

**Comment by sirblazzit** [comment]
Would it be possible to add a toggle instead? 
Literally what the plugin is at the moment, but application specific? 
BarRaider does have a 1-Device-Per-Button application selector like the OP requested, so you'd need 2 buttons.
A toggle would be nice, so you can toggle your Firefox, Spotify, Game Audio etc, and only use 1 button each
![image](https://github.com/fredemmott/StreamDeck-AudioSwitcher/assets/46121899/1b90e28d-f2ac-49e6-9154-3b3b80ab8014)
