### ISSUE TITLE
Toggle Between Multiple Device Profiles

### ISSUE THREAD

**Issue by nfrankish** [fredemmott/StreamDeck-AudioSwitcher#91]
**Is your feature request related to a problem? Please describe.**
I generally run two device profiles
Headphones
- Input and communication device updated to headphones
- output device set to headphones
Speakers
- Input and Communication device set to usb microphone
- output device set to speakers

**Describe the solution you'd like**
An option to have profiles that you toggle between, that shows which mode is currently set "at a glance"

**Describe alternatives you've considered**
I have considered setting up a button for each action, but that is space consuming.

**Comment by fredemmott** [comment]
This can be done with the built-in 'multi action switch' functionality

**Comment by nfrankish** [comment]
The multi-action doesnt provide the option to show you which profile you currently have selected.

**Comment by fredemmott** [comment]
multi-action *switch* lets you set a different icon and text to be displayed for each of the two 'profiles'.
