### ISSUE TITLE
Add a listen toggle

### ISSUE THREAD

**Issue by AlexanderIsom** [fredemmott/StreamDeck-AudioSwitcher#94]
**Is your feature request related to a problem? Please describe.**
I have an audio interface that allows for custom voices and midi playback, whenever I use this however I cannot hear myself when I'm not using the audio interface as a playback device.

**Describe the solution you'd like**
I'd like an additional button to be able to toggle listening to this device back through a specific device

**Describe alternatives you've considered**
I've looked for other stream deck plugins, as well as scripts, however I belive it would be a great addition to the plugin

**Additional context**
none

**Comment by fredemmott** [comment]
This would probably be a better for fit for StreamDeck-AudioToggle - though I love the idea. That said, I don't know a way to do this :( If you know of existing open source projects (streamdeck or not) that are able to do this, that would be very useful.
