### ISSUE TITLE
Plugin doesn't show when Elgato Wave 3 is muted on the mic

### ISSUE THREAD

**Issue by ForboJack** [fredemmott/StreamDeck-AudioSwitcher#95]
When I use the plugin to mute my Elgato Wave 3 the led on the mic gets red (showing that it's muted). But sometimes when I mute the mic with the touch button on the mic, the plugin doesn't realize this and doesn't switch states. Mostly it doesn't work after a restart of my PC. Sometimes it starts randomly working again and then it keeps working until it doesn't after a few restarts.

**Comment by fredemmott** [comment]
Sorry, I'm going to close it as I can't act on it.

That said, when this is happening, does it show up as muted in mmsys.cpl?

 win+r, mmsys.cpl, right click -> properties ->levels

![image](https://user-images.githubusercontent.com/360927/205092722-72c895a6-07a4-40d8-ae69-91e964a1706e.png)

If not: please report this as a bug to Elgato; it's not something I'd be able to fix even with the hardware
If it does show as muted, I might be able to fix this if I had the hardware, but I don't :(

**Comment by fredemmott** [comment]
If you're on a mac, the equivalent is this in 'audio midi setup':

<img width="763" alt="Untitled" src="https://user-images.githubusercontent.com/360927/205093466-3e5d39d6-df11-404f-8519-469629fbac1d.png">
